name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: swiftlint --strict

  test_on_macOS:
    name: Build and Test on macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: ./build.sh
    - name: Run tests
      run: ./test.sh

  test_on_Linux:
    name: Build and Test on Linux
    runs-on: ubuntu-latest
    container: swift:6.0-noble
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./build.sh
      - name: Run tests
        run: ./test.sh
